# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='completedtask',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.DeleteModel(
            name='CompletedTask',
        ),
    ]
