# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletedTasks',
            new_name='CompletedTask',
        ),
    ]
